### ISSUE TITLE
URLSearchParams no longer exported by "svelte/reactivity"

### ISSUE THREAD

**Issue by mrbelderock** [Ernxst/svelte-query-params#12]
### Describe the bug

It looks like this library is looking for a URLSearchParams object from "svelte/reactivity", which I think no longer exists. Svelte now exports a reactive "SvelteURL".

I'm guessing the constant updates to Svelte 5 RC have broken this lib?

It looks super useful otherwise! Hard to believe Svelte doesn't have capability built in for syncing state easily with URLSearchParams.

### Reproduction

Start new Svelte5 project, follow instructions from the docs. (I'm using Deno, but that shouldn't matter.)

Breaks with:  

No matching export in "node_modules/.deno/svelte@5.0.0-next.259/node_modules/svelte/src/reactivity/index-client.js" for import "URLSearchParams"

    node_modules/.deno/svelte-query-params@0.2.3/node_modules/svelte-query-params/dist/index.svelte.js:24:9:
      24 │ import { URLSearchParams as reactive_URLSearchParams } from "svelte/reactivity";

### System Info

```shell
Deno 2.00 rc5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/Ernxst/svelte-query-params/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Ernxst/svelte-query-params/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/Ernxst/svelte-query-params/blob/main/docs).
- [X] Check that there isn't [already an issue](https://github.com/Ernxst/svelte-query-params/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Ernxst/svelte-query-params/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ernxst** [comment]
There was a leftover todo because svelte renamed an exported class (see this [release](https://github.com/sveltejs/svelte/releases/tag/svelte@5.0.0-next.169)) and I was originally planning to wait until rc to make this change, but it seems it's been stable for quite a while now. This should be fixed in [`0.2.4`](https://github.com/Ernxst/svelte-query-params/releases/tag/svelte-query-params%400.2.4).
